# Generated by Django 6.0.5 on 2026-05-19 05:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('erp_app', '0002_notification'),
    ]

    operations = [
        migrations.CreateModel(
            name='IDCard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('card_type', models.CharField(choices=[('student', 'Student'), ('employee', 'Employee')], max_length=20)),
                ('file', models.FileField(upload_to='id_cards/')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('employee', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='id_cards', to='erp_app.employee')),
                ('student', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='id_cards', to='erp_app.student')),
            ],
            options={
                'ordering': ['-uploaded_at'],
            },
        ),
    ]
