# Generated by Django 6.0.5 on 2026-05-20 03:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('erp_app', '0005_student_user_certificate'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='certificate',
            options={'ordering': ['-issue_date'], 'permissions': [('can_issue_certificates', 'Can issue certificates')]},
        ),
        migrations.AddField(
            model_name='certificate',
            name='internship_details',
            field=models.TextField(blank=True, help_text='Project description, duration, or other internship details'),
        ),
    ]
