# Generated by Django 6.0.5 on 2026-05-20 06:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('erp_app', '0006_alter_certificate_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='certificate',
            name='certificate_type',
            field=models.CharField(choices=[('course', 'Course'), ('internship', 'Internship'), ('workshop', 'Workshop')], max_length=20),
        ),
    ]
