# Generated by Django 6.0.5 on 2026-05-20 09:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('erp_app', '0008_setup_roles_and_permissions'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='is_intern',
            field=models.BooleanField(default=False),
        ),
    ]
