# Generated by Django 5.2.14 on 2026-06-03 18:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('erp_app', '0012_passwordresetcode'),
    ]

    operations = [
        migrations.AddField(
            model_name='mentor',
            name='department',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='erp_app.department'),
        ),
    ]
