# Generated by Django 5.2.14 on 2026-06-03 18:44

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('erp_app', '0013_mentor_department'),
    ]

    operations = [
        migrations.AddField(
            model_name='mentor',
            name='joined_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='employee',
            name='joined_date',
            field=models.DateField(default=datetime.date.today),
        ),
    ]
