# Generated by Django 6.0.5 on 2026-06-11 10:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('erp_app', '0015_attendance'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendance',
            name='date',
            field=models.CharField(max_length=10),
        ),
    ]
